### ISSUE TITLE
[Migration] TypeError: Cannot read properties of null (reading 'useContext')

### ISSUE THREAD

**Issue by MikeCodeur** [MikeCodeur/react-prerequis-debutants#18]
✓ Compiled /alone/exercise/[exerciseId] in 1320ms (1596 modules)
 ✓ Compiled /alone/solution/[solutionId] in 392ms (1597 modules)
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
TypeError: Cannot read properties of null (reading 'useContext')
    at t.useContext (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:163120)
    at usePathname (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/client/components/navigation.js:122:34)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/client/components/error-boundary.js:129:50)
    at ai (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:6505)
    at /home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11284
    at ab (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13038)
    at e (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46298)
    at aS (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at ag (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7923)
    at /home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13014
    at ab (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13038)
    at ab (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:43088)
    at e (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46298)
    at aS (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at e (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46613)
    at aS (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at ag (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7923)
    at /home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13014
    at ab (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13038)
    at e (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46298)
    at aS (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at /home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55195
    at /home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55862
    at a$ (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:55870)
    at Timeout._onTimeout (/home/mike/repo/mikecodeur/course-app/node_modules/.pnpm/next@14.0.4_@babel+core@7.24.7_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:4037)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
 ⨯ Internal error: TypeError: Cannot read properties of null (reading 'useContext')

**Comment by HAMADOns** [comment]
faut juste nettoyer le cash de l'editeur

**Comment by HAMADOns** [comment]
L'app a juste besoin d'un nettoyage cash pour faire disparaitre ce message

**Comment by HAMADOns** [comment]
Je close comme je n'ai plus cette erreur à 2 reprises, si elle se présente de nouveau il faut nettoyer l'environnement
